apiVersion: v1
kind: Namespace
metadata:
  name: vault
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: vault
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-server-tls
  namespace: vault
spec:
  commonName: localhost
  dnsNames: [ "localhost", "vault.vault.svc.cluster.local" ]
  ipAddresses: [ 127.0.0.1 ]
  secretName: vault-server-tls
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
