---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: gui-mapping
  namespace: faces
spec:
  hostname: "demo.cluster.local"
  prefix: /faces/
  service: faces-gui.faces
  rewrite: /
  timeout_ms: 0
