---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: face-mapping
  namespace: faces
spec:
  hostname: "demo.cluster.local"
  prefix: /face/
  service: face.faces
  timeout_ms: 250
  retry_policy:
    retry_on: 5xx
    num_retries: 1
